name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: |
          mkdir -p dist
          GOOS=windows GOARCH=amd64 go build -o dist/go-dev-mcp-windows-amd64.exe ./cmd/server
          GOOS=darwin GOARCH=amd64 go build -o dist/go-dev-mcp-darwin-amd64 ./cmd/server
          GOOS=linux GOARCH=amd64 go build -o dist/go-dev-mcp-linux-amd64 ./cmd/server

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/go-dev-mcp-windows-amd64.exe
            dist/go-dev-mcp-darwin-amd64
            dist/go-dev-mcp-linux-amd64
          draft: false
          prerelease: false
          generate_release_notes: true